// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

type User struct {
	ID        interface{}
	FullName  string
	Email     string
	Password  string
	CreatedAt interface{}
}
